services:
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: chatapp
      DATABASE_USER: mongo 
      DATABASE_PASS: mongo
      DATABASE_URI:  mongodb://database:27017
    ports:
      - '4000:4000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: chatapp
      MONGO_INITDB_ROOT_PASSWORD: mongo